// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDdxCgauBsh3SCbDY8zZ1HanJo8gj1cJP8',
    appId: '1:489550094744:web:76297437770cf43a158bed',
    messagingSenderId: '489550094744',
    projectId: 'loopcart-ae408',
    authDomain: 'loopcart-ae408.firebaseapp.com',
    storageBucket: 'loopcart-ae408.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAxKgVvAwWrB4ZOoZfQpLi7gJcWkUDmKfY',
    appId: '1:489550094744:android:287743d7249a70ba158bed',
    messagingSenderId: '489550094744',
    projectId: 'loopcart-ae408',
    storageBucket: 'loopcart-ae408.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCVuRBNmacgAT9bGQzXyzeuow08bdC19q8',
    appId: '1:489550094744:ios:b444f19e386b6fed158bed',
    messagingSenderId: '489550094744',
    projectId: 'loopcart-ae408',
    storageBucket: 'loopcart-ae408.appspot.com',
    iosBundleId: 'com.example.loopCart',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCVuRBNmacgAT9bGQzXyzeuow08bdC19q8',
    appId: '1:489550094744:ios:b444f19e386b6fed158bed',
    messagingSenderId: '489550094744',
    projectId: 'loopcart-ae408',
    storageBucket: 'loopcart-ae408.appspot.com',
    iosBundleId: 'com.example.loopCart',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDdxCgauBsh3SCbDY8zZ1HanJo8gj1cJP8',
    appId: '1:489550094744:web:7912fc3b696e6aa0158bed',
    messagingSenderId: '489550094744',
    projectId: 'loopcart-ae408',
    authDomain: 'loopcart-ae408.firebaseapp.com',
    storageBucket: 'loopcart-ae408.appspot.com',
  );
}
